server:
   port: 8080
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db
    password: rootTest
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE

#public private keys
app:
  jwt:
    key-alias: signjwt
    private-key-passphrase: testing123
    keystore-location: keys/keystore.jks
    keystore-password: testing123
  api:
    apilayer: MjgVMZX80YrxmLivxwlnnZpE04PvNhB1